//-------------------------------------------------------------------------------------------------
// 事件名称字符串
// WHJ
//-------------------------------------------------------------------------------------------------

// 这个地方使用枚举之后，加导出会编译不过，不加其他的模块想用也会报错，只好先用class
export default class EventName  
{
    public static EVENT_DO_LOGIN                        = "EVENT_DO_LOGIN";			                // 执行登录状态切换
	public static EVENT_DO_LOAD_SCENE_COMPLETE          = "EVENT_DO_LOAD_SCENE_COMPLETE";           // 切换场景完成
    public static EVENT_DO_FOCUS_STATE                  = "EVENT_DO_FOCUS";					        // 焦点
    public static EVENT_DO_QUIT_STATE                   = "EVENT_DO_QUIT";						    // 退出
	public static EVENT_DO_PAUSE_STATE                  = "EVENT_DO_PAUSE";					        // 暂停
	public static EVENT_DO_AUTO_ROOM                    = "EVENT_DO_AUTOROOM";					    // 自动返回房间;
	public static EVENT_DO_SHARE_CALLBACK               = "EVENT_DO_SHARE_CALLBACK";                // 分享回调功能
	public static EVENT_DO_LOGIN_TIMER                  = "EVENT_DO_LOGINTIMER";				    // 登录定时器
	public static EVENT_DO_AUTO_OTHER_RECORD            = "EVENT_DO_OTHER_RECORD";               	// 自动查看他人战绩

    // UI相关
	public static EVENT_UI_ITEM_REFRESH                 = "EVENT_UI_ITEM_REFRESH";           	    // 刷新界面道具显示
    public static EVENT_UI_SAY_HELLO                    = "EVENT_UI_SAY_HELLO";
    public static EVENT_UI_ZHUAN_JU_HUA                 = "EVENT_UI_ZHUAN_JU_HUA"; 
	public static EVENT_UI_REFRESH_NAME				    = "EVENT_UI_REFRESH_NAME";				    // 刷新名字
	public static EVENT_UI_REFRESH_HEAD 				= "EVENT_UI_REFRESH_HEAD";                  // 刷新头像
	public static EVENT_UI_REFRESH_ICON				 	= "EVENT_UI_REFRESH_ICON";				  	// 刷新游戏头像
    public static EVENT_UI_REFRESH_ONCLICK_NOTICE       = "EVENT_UI_REFRESH_ONCLICK_NOTICE";        // 刷新公告点击
    public static EVENT_UI_REFRESH_LOGIN_PLAN           = "EVENT_UI_REFRESH_LOGIN_PLAN";            // 刷新登录步骤
    public static EVENT_UI_BIND_PHONE_CODE              = "EVENT_UI_REFRESH_PHONE_CODE";            // 刷新获取验证码按钮状态;
    public static EVENT_UI_TIMERESH_BUTTON              = "EVENT_UI_TIMERESH_BUTTON";               // 刷新时间获取按钮状;
    public static EVENT_UI_UILLBINDBUTTON               = "EVENT_UI_UILLBINDBUTTON";                // 刷新大厅绑定手机按钮状态;
    public static EVENT_UI_BIND_IDCARD_STATEINFO        = "EVENT_UI_BIND_IDCARD_STATEINFO";         // 刷新大厅身份绑定按钮状态;
	public static EVENT_UI_REFRESH_MAIL_RED_POINT       = "EVENT_UI_REFRESH_MAIL_RED_POINT";        // 刷新显示邮箱红点
	public static EVENT_UI_REFRESH_HIDE_MAIL_RED_POINT  = "EVENT_UI_REFRESH_HIDE_MAIL_RED_POINT";   // 刷新隐藏邮箱红点
	public static EVENT_UI_REFRESH_MAIL 				= "EVENT_UI_REFRESH_MAIL";                  // 刷新邮箱界面
	public static EVENT_UI_REFRESH_MAIL_REWARD_STATE    = "EVENT_UI_REFRESH_MAIL_REWARD_STATE";     // 刷新邮件领取状态
	public static EVENT_UI_BIND_FRIEND_INFO             = "EVENT_UI_BIND_FRIEND_INFO";              // 刷新所有绑定好友信息;
	public static EVENT_UI_BIND_FRIEND         		    = "EVENT_UI_BIND_FRIEND";                   // 刷新绑定id;
	public static EVENT_UI_PLAY_COUNT_REWARD   		    = "EVENT_UI_PLAY_COUNT_REWARD";             // 刷新玩游戏奖励;
	public static EVENT_UI_GET_BIND_FRIEND_REWARD  	    = "EVENT_UI_GET_BIND_FRIEND_REWARD";        // 刷新被绑定奖励;
	public static EVENT_UI_GET_PLAY_COUNT_REWARD   	    = "EVENT_UI_GET_PLAY_COUNT_REWARD";         // 刷新玩够几局游戏奖励;
	public static EVENT_UI_REFRESH_SHOP				    = "EVENT_UI_REFRESH_SHOP";                  // 刷新商店界面;
	public static EVENT_UI_REFRESH_SHOP_ITEM			= "EVENT_UI_REFRESH_SHOP_ITEM";             // 刷新商店道具;
	public static EVENT_UI_REFRESH_SHOPTEXTURE		    = "EVENT_UI_REFRESH_SHOPTEXTURE";           // 刷新商城贴图
    public static EVENT_UI_GET_WTCHATLOGINSHOW  	    = "EVENT_UI_GET_WTCHATLOGINSHOW";           // 刷新微信登录按钮;
	public static EVENT_UI_SET_SHOPSELECTBUTTON  	    = "EVENT_UI_SET_SHOPSELECTBUTTON";          // 刷新商店当前选择标签;
	public static EVENT_UI_CONSUME_REFRESH			    = "EVENT_UI_CONSUME_REFRESH";               // 刷新房间消耗;
	public static EVENT_UI_LOAD_SLIDESHOW_TEX_END		= "EVENT_UI_LOAD_SLIDESHOW_TEX_END";        // 加载轮播图完成
	public static EVENT_UI_SHOW_MESSAGE_BY_ID           = "EVENT_UI_SHOW_MESSAGE_BY_ID";            // 显示提示消息（根据id）
	public static EVENT_UI_SHOW_MESSAGE_BY_STR          = "EVENT_UI_SHOW_MESSAGE_BY_STR";           // 显示提示消息（根据str）
	public static EVENT_UI_REQUEST_PROXYINFO 			= "EVENT_UI_REQUEST_PROXYINFO";             // 请求代理信息
	public static EVENT_UI_REFRESH_PROXYINFO 			= "EVENT_UI_REFRESH_PROXYINFO";             // 刷新代理信息
	public static EVENT_UI_STATISTICS					= "EVENT_UI_STATISTICS";                    // 刷新统计
	public static EVENT_UI_PHOTO_FRAME				    = "EVENT_UI_PHOTO_FRAME";                   // 刷新临时头像框
	public static EVENT_UI_USEITEM					    = "EVENT_UI_USEITEM";                       // 刷新使用道具
	public static EVENT_UI_NEW_PHOTO_FRAME			    = "EVENT_UI_NEW_PHOTO_FRAME";               // 刷新新的头像框
	public static EVENT_UI_REFRESH_STATISTICS_GAME_INFO = "REFRESH_STATISTICS_GAME_INFO";           // 刷新战绩统计信息
	public static EVENT_UI_REFRESH_RECORD_INFO          = "REFRESH_RECORD_INFO";                    // 刷新战绩信息 
	public static EVENT_UI_MATCH_STATIC_INFO            = "EVENT_UI_MATCH_STATIC_INFO";             // 刷新比赛静态信息 
	public static EVENT_UI_LOCATION					    = "EVENT_UI_LOCATION";                      // 刷新定位信息
	public static EVENT_UI_UIROPI						= "EVENT_UI_UIROPI";                        // 刷新玩家信息
	public static EVENT_UI_REFRESH_MATCH				= "EVENT_UI_REFRESH_MATCH";                 // 刷新比赛界面
	public static EVENT_UI_REFRESH_MATCH_ITEM			= "EVENT_UI_REFRESH_MATCH_ITEM";            // 刷新比赛信息
	public static EVENT_UI_SET_MATCHTAG  	 			= "EVENT_UI_SET_MATCHTAG";                  // 刷新比赛当前选择标签
	public static EVENT_UI_SINGLE_MATCH 			 	= "EVENT_UI_SINGLE_MATCH";                  // 刷新比赛单条信息
	public static EVENT_UI_MATCH_PULL 			 	    = "EVENT_UI_MATCH_PULL";                    // 服务器拉进比赛
	public static EVENT_UI_MATCH_BYE 			 	 	= "EVENT_UI_MATCH_BYE";                     // 比赛轮空
	public static EVENT_UI_MATCH_PROMOTION	 	 	    = "EVENT_UI_MATCH_PROMOTION";               // 比赛晋级
	public static EVENT_UI_MATCH_COMPLETE	 	 	 	= "EVENT_UI_MATCH_COMPLETE";                // 比赛完成,等待其他玩家
	public static EVENT_UI_MATCH_INMATCH	 	 	 	= "EVENT_UI_MATCH_INMATCH";                 // 断线重连时在比赛内提示
	public static EVENT_UI_MATCH_RANKING	 		 	= "EVENT_UI_MATCH_RANKING";                 // 比赛排名
	public static EVENT_UI_MATCH_RANKINGS	 		 	= "EVENT_UI_MATCH_RANKINGS";                // 复选赛排名
	public static EVENT_UI_REFRESH_PERSONALDATA	 	    = "EVENT_UI_REFRESH_PERSONALDATA";          // 刷新个人信息
    public static EVENT_UI_REFRESH_BINDBANKCARD	 	    = "EVENT_UI_REFRESH_BINDBANKCARD";          // 刷新银行卡信息
    public static EVENT_UI_REFRESH_BANKNAME	 	        = "EVENT_UI_REFRESH_BANKNAME";              // 刷新选择的银行卡
	public static EVENT_UI_REFRESH_MASTERSCORE	        = "EVENT_UI_REFRESH_MASTERSCORE";           // 刷新大师分
	public static EVENT_UI_REF_MATCHREMAIN	     	    = "EVENT_UI_REF_MATCHREMAIN";               // 刷新剩余牌桌数
	public static EVENT_UI_REF_REWARDINFO 	     	    = "EVENT_UI_REF_REWARDINFO";                // 刷新奖励
	public static EVENT_UI_REF_MATCHRULE 	     	 	= "EVENT_UI_REF_MATCHRULE";                 // 刷新帮助
	public static EVENT_UI_REF_MATCHRULEBYID 	   	 	= "EVENT_UI_REF_MATCHRULEBYID";             // 通过ID刷新帮助
	public static EVENT_UI_REF_MATCHCONSUME     	 	= "EVENT_UI_REF_MATCHCONSUME";              // 选择消耗
	public static EVENT_UI_REF_MATCHCURPLAYER     	    = "EVENT_UI_REF_MATCHCURPLAYER";            // 刷新当前人数
    public static EVENT_UI_REF_MATCHJUSHOWDOWN          = "EVENT_UI_REF_MATCHJUSHOWDOWN";           // 比赛本局结算;
	public static EVENT_UI_REF_LOADPROGRESS				= "EVENT_UI_REF_LOADPROGRESS";				// 刷新资源加载进度
	public static EVENT_UI_LOADCOMPLETED				= "EVENT_UI_LOADCOMPLETED";					// 资源加载完成
	public static EVENT_UI_STARTLOADRES					= "EVENT_UI_STARTLOADRES";					// 开始加载资源
	public static EVENT_UI_SHOW_RECORD_DETAIL			= "EVENT_UI_SHOW_RECORD_DETAIL"				// 显示战绩细节UI
	public static EVENT_UI_SHOW_CHRYSANTHEMUM_BY_STR	= "EVENT_UI_SHOW_CHRYSANTHEMUM_BY_STR"		// 菊花显示文字
	public static EVENT_UI_CLOSE_CHRYSANTHEMUM_BY_STR	= "EVENT_UI_CLOSE_CHRYSANTHEMUM_BY_STR"		// 关闭菊花

    // 游戏大厅网络消息 格式:[NET_TO_XXXX]
    public static NET_DO_LOGIN		        		    = "LOGIN";								    // 游戏登录消息;
    public static NET_DO_SYNCDATA		        		= "SyncData";							    // 游戏同步角色信息;
	public static NET_DO_TOKEN_ERROR					= "LTERROR";							    // TOKEN错误重新验证;
    public static NET_DO_S_CREATEROLE         		    = "PLY_NULL";							    // 服务器回执需创建角色;
    public static NET_DO_C_CREATEROLE         		    = "CT_PLY";							        // 游戏创建角色消息;
    public static NET_DO_S_SYNCLOGINPLAYER    		    = "LPLY";				     			    // 服务器返回登录玩家基础信息
    public static NET_DO_ITEMLIST_REFRESH     		    = "SICU";                   		 	    // 刷新背包道具
    public static NET_DO_ONLYITEM_REFRESH 		 	    = "RefreshItem";            			    // 刷新单个道具
    public static NET_DO_USEITEM_REFRESH				= "UseItem";							    // 使用道具
	public static NET_DO_CREATE_PRIVATE_ROOM  		    = "PCM";                    			    // 创建房间
    public static NET_DO_C_ENTER_ROOM         		    = "PEM" ;                   			    // 加入房间;
    public static NET_DO_COMMON_ERROR         		    = "ERR";                    			    // 错误
    public static NET_DO_GOBACK_GAME					= "GoBackGame";			 		            // 返回房间;
    public static NET_DO_BIND_MOLILE                    = "BMNC";                                   // 绑定手机号;
    public static NET_DO_JOINTROOM                      = "RQSRT";								    // 查找房间类型;
    public static NET_DO_SENDCHAT                       = "CR";								        // 聊天;
    public static NET_DO_INITBINDINFO                   = "INITBI";                                 // 刷新角色绑定信息;
    public static NET_DO_BIND_IDCARD_BDIC               = "BINDIDCARD" ;                            // 绑定身份证; 
    public static NET_DO_REQUEST_PROXY                  = "RPROXY";							        // 请求代理信息;
    public static NET_DO_BIND_PPROXY                    = "BPROXY";							        // 绑定代理信息;
    public static NET_DO_MAIL_SYSTEM_REQUESTMAIL        = "RMAIL";               				    // 接受系统邮件
    public static NET_DO_MAIL_SYSTEM_REWARD             = "SRAD";                   			    // 接收系统礼物
    public static NET_DO_MAIL_COMMON_REWARD             = "CRAD";                   			    // 接收普通礼物
    public static NET_DO_MAIL_CHECK                     = "MFG";                    			    // 邮件通知显示红点
    public static NET_DO_MAIL_DELETECMAIL               = "DCM";								    // 删除普通邮件
    public static NET_DO_MAIL_DELETESMAIL               = "DSM";								    // 删除系统邮件
    public static NET_DO_GAME_OFFLINE                   = "ROFFLINE";							    // 玩家离线;
    public static NET_DO_GAME_ONLINE                    = "RONLINE";							    // 玩家在线;
    public static NET_DO_SEND_ROLE_LOCATION             = "DISINFO";							    // 同步自己位置;
    public static NET_DO_REVC_ROLE_LOCATION             = "GETDISINFO";						        // 获取其它玩家位置;
    public static NET_DO_BIND_FRIEND_INFO               = "ABFI";   							    // 请求所有绑定好友信息;
    public static NET_DO_BIND_FRIEND                    = "RBF";                                    // 申请绑定id;
    public static NET_DO_PLAY_COUNT_REWARD              = "RPCR";                                   // 申请获得玩游戏奖励;
    public static NET_DO_GET_BIND_FRIEND_REWARD         = "AGBFR";  						 	    // 请求获取被绑定奖励;
    public static NET_DO_GET_PLAY_COUNT_REWARD          = "AGPCR";  							    // 请求获取玩够几局游戏奖励;
    public static NET_DO_SHARE_GET_REWARD               = "SGR";        						    // 每日首次分享获取奖励
    public static NET_DO_SHARE_RECV_REWARD              = "SRR";        						    // 接受玩家信息
    public static NET_DO_SYNC_SERVERTIME                = "SyncTime";							    // 接收服务器时间
    public static NET_DO_RECEVESEVEROPI                 = "ROPI";							        // 接收其他玩家信息
    public static NET_DO_STATISTICS_DATA                = "SSD";								    // 接受统计信息
	public static NET_DO_STATISTICS_SRC                 = "SRC";								    // 收集统计信息
    public static NET_DO_INTERACTITEM                   = "InteractItem";				  		    // 刷新使用道具;
    public static NET_DO_STATISTICS_GAME_INFO           = "RMST";                                   // 接收游戏统计消息
	public static NET_DO_GET_RECORD_INFO                = "SFR";                                    // 请求战绩信息
	public static NET_DO_GET_RECORD_DETAILED_INFO       = "SFR_DC";                                 // 请求战绩详细信息
    public static NET_DO_GET_MATCH_DETAILED_INFO        = "SFR_ADC";                                // 请求比赛战绩详细信息
    public static NET_DO_GET_RECORD_NODE_INFO           = "SFR_DNODE";                              // 请求战绩房间节点信息
    public static NET_DO_SHOP_BUY                       = "SHOP_BUY";						  	    // 商城购买物品;
    public static NET_DO_MATCH_JOIN_ROOM                = "MJR";								    // 加入私房比赛;
    public static NET_DO_CHECK_ISMATCH_ROOM             = "GoBackGame";						        // 检查是否比赛房间内
	public static NET_DO_GET_PERSONAL_DATA              = "GPSN" ;                         	        // 获取个人信息; 
    public static NET_DO_GET_BANKCARD_DATA              = "GBCN" ;                         	        // 获取绑定银行卡信息;
    public static NET_DO_GET_MASTER_RDATA               = "RQQYSCDE" ;                              // 请求大师分信息;
	public static NET_DO_GET_REWARD_DATA                = "RQQYEXMN" ;                              // 请求奖励余额;
	public static NET_DO_GET_CASH_DATA	                = "RQQYDRMN" ;                              // 提现;
	public static NET_DO_UPDATE_BALANCE	                = "WBUB" ;                           	    // 更新宝豆;
	public static NET_DO_RANK_BAODOU                    = "RMT" ;                           	    // 宝豆排行榜;
	public static NET_DO_GET_GAME_RECORD_DATA           = "LOGGR";                                  // 比赛回放日志数据
	public static NET_DO_GET_HL_DATA                    = "HLGET";                                  // 请求跑马灯数据
	public static NET_DO_UPDATE_HL_DATA                 = "HLUPDATE";                               // 更新跑马灯数据
}
